project:
  type: website
  output-dir: docs

website:
  title: "Microbiome Phylogenetic Tree"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lrt666
      - icon: twitter
        href: https://twitter.com
      - icon: facebook
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: style.css

editor: visual

posts:
  - folder: posts

